### PR TITLE
Distance calculations

### PR DESCRIPTION
**Pull request by joshuakrauchi**
- CHANGED FOLDER STRUCTURE, pull from dev ASAP after pull request merge.
- Added functions for determining distance between player and badges.

### CODE REVIEW

**Review by MoBaydoun — APPROVED** [review]
LGTM! Just don't forget to change vercel's directory.

**Review by notyalcs — APPROVED** [review]
Looks good

**Review by Mazianos — APPROVED** [review]
Looks fantastic friendo

**Review by PariyaKasaeian — APPROVED** [review]
everything looks fine!

**Pull request merged**
