### PR TITLE
Hopefully the last push to main before the presentation

### PR DESCRIPTION
**Pull request by joshuakrauchi**
- Added pretty much everything.

### CODE REVIEW

**Review by Mazianos — APPROVED** [review]
Poggers PR

**Review by notyalcs — APPROVED** [review]
29k additions, 29k deletions. No more project. Looks good.

**Review by MoBaydoun — APPROVED** [review]
image-removebg-preview (3)
LGTM!

**Comment by MoBaydoun** [comment]
image (4)
Thanks for all the work guys!

**Review by gauravkochar87 — APPROVED** [review]

**Pull request merged**
